# .sops.yaml - sops configuration
# Add your age public keys below
keys:
  - &main age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Main-MacBook-Pro
  - &work age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Work-MacBook-Pro
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *main
        - *work
